# Generated by Django 2.1 on 2018-08-24 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advisory',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='文章ID')),
                ('title', models.CharField(max_length=50, verbose_name='标题')),
                ('body', models.TextField(verbose_name='内容')),
                ('author', models.CharField(max_length=50, verbose_name='作者')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='产品ID')),
                ('title', models.CharField(max_length=50, verbose_name='标题')),
                ('author', models.CharField(max_length=50, verbose_name='作者')),
                ('produce', models.CharField(max_length=50, verbose_name='产区')),
                ('capacity', models.CharField(help_text='单位：ml', max_length=50, verbose_name='干型 含量')),
                ('degree', models.CharField(help_text='单位：%vol', max_length=50, verbose_name='度数')),
            ],
        ),
    ]
